# Configuration Jekyll pour GitHub Pages
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-cayman
title: Oussama Wachofi — Portfolio
description: Élève ingénieur en Sécurité et Qualité des Réseaux
